// Here all my recent projects and qualifications
import images from './images'

const projects = [
  {
    id: 33,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectRepo: 'https://github.com/FabKaiz/typescript-buzzfeed-clone',
    img: images.buzzfeed,
    codeLanguage: 'React, TypeScript, NodeJS et axios',
  },
  {
    id: 32,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://framer-motion-react-fabkaiz.netlify.app/',
    projectRepo: 'https://github.com/FabKaiz/framer-motion-react',
    img: images.framerMotion,
    codeLanguage: 'React, du CSS et Framer Motion',
  },
  {
    id: 31,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://react-custom-content-loader-fabkaiz.netlify.app/',
    projectRepo: 'https://github.com/FabKaiz/react-custom-content-loader',
    img: images.contentLoader,
    codeLanguage: 'React et React content loader',
  },
  {
    id: 30,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://react-spring-mounting-unmounting.netlify.app/',
    projectRepo: 'https://github.com/FabKaiz/react-mount-unmount-animations',
    img: images.reactSpring1,
    codeLanguage: 'React et React Spring',
  },
  {
    id: 29,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    figmaLink:
      'https://dribbble.com/shots/15067925--Freebie-CRAPPO-Cryptocurrency-Website',
    projectSite: 'https://crappo-crypto-ts.vercel.app/',
    projectRepo: 'https://github.com/FabKaiz/crappo-crypto-ts',
    img: images.crappoCrypto,
    codeLanguage: 'NextJs, Typescript, Scss et React Icons',
  },
  {
    id: 28,
    title: 'Data processing app',
    description: `Maquette dribbble d'une app de traitement des données, reproduit avec `,
    figmaLink:
      'https://dribbble.com/shots/15102679-Dark-Landing-Page-Concept-For-Data-Processing-Company',
    projectSite: 'https://data-landing-nextjs.vercel.app/',
    projectRepo: 'https://github.com/FabKaiz/data-landing-nextjs',
    img: images.dataProcessing,
    codeLanguage: 'NextJs, Scss',
  },
  {
    id: 27,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    figmaLink:
      'https://dribbble.com/shots/11018704/attachments/2612947?mode=media',
    projectSite: 'https://woodies-nextjs.vercel.app/',
    projectRepo: 'https://github.com/FabKaiz/woodies-nextjs',
    img: images.woodies,
    codeLanguage: 'NextJs, Scss',
  },
  {
    id: 26,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://instagram-clone-nextjs-gamma.vercel.app/',
    projectRepo: 'https://github.com/FabKaiz/instagram-clone-nextjs',
    img: images.instaClone,
    codeLanguage: 'NextJs, Next Auth, Recoil, Tailwind, Firebase et OAuth',
  },
  {
    id: 25,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://nextjs-sanity-medium.vercel.app/',
    projectRepo: 'https://github.com/FabKaiz/nextjs-sanity-medium',
    img: images.mediumClone,
    codeLanguage: 'NextJs, Tailwind, TypeScript et Sanity',
  },
  {
    id: 24,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://fabkaiz-admin-panel.netlify.app/',
    projectRepo: 'https://github.com/FabKaiz/admin-panel',
    img: images.admin,
    codeLanguage:
      'React, Material Ui Icons - Table - Data-grid, Recharts, Scss, React Router V6, React Circular Progressbar',
  },
  {
    id: 23,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://sanity-stripe-shop.vercel.app/',
    projectRepo: 'https://github.com/FabKaiz/sanity-stripe-shop',
    img: images.sanityStripe,
    codeLanguage:
      'NextJs en frontend, Sanity pour le backend, Stripe, canvas-confetti',
  },
  {
    id: 22,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://travel-blog-snowy.vercel.app/',
    projectRepo: 'https://github.com/FabKaiz/travel-blog',
    img: images.travelBlog,
    codeLanguage:
      'NextJs en frontend, Sanity pour le backend, mapboxGL, Groq, NProgress',
  },
  {
    id: 21,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://space-tourism-react-fabkaiz.netlify.app/',
    projectRepo: 'https://github.com/FabKaiz/react-space-tourism',
    img: images.spaceTourism,
    codeLanguage:
      'React, React Router v6, framer-motion, React Transition Group, sass',
  },
  {
    id: 20,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://javascript-minigames.netlify.app/',
    projectRepo: 'https://github.com/FabKaiz/javascript-games',
    img: images.JavaScriptGame,
    codeLanguage: 'vanilla JavaScript',
  },
  {
    id: 1,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    figmaLink:
      'https://www.figma.com/file/yvClSI9AZBRX8UaaGEByF3/Modern-UI%2FUX%3A-Gericht?node-id=53%3A2',
    projectSite: 'https://gerich-restaurant.netlify.app/',
    projectRepo: 'https://github.com/FabKaiz/gerich-restaurant',
    img: images.Port14,
    codeLanguage: 'React',
  },
  {
    id: 2,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    figmaLink:
      'https://www.figma.com/file/lz9lLpFHMxHm2odnwM3R0z/gpt3?node-id=0%3A1',
    projectSite: 'https://gpt3-modern-react.netlify.app/',
    projectRepo: 'https://github.com/FabKaiz/modern-gpt3-react',
    img: images.Port13,
    codeLanguage: 'React',
  },
  {
    id: 3,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://fabkaiz.github.io/gsap3-bella/',
    projectRepo: 'https://github.com/FabKaiz/gsap3-bella',
    img: images.Port10,
    codeLanguage: 'GSAP, ScrollTrigger, BarbaJs, Smooth Scrolling..',
  },
  {
    id: 4,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://fabienchareun.com/',
    projectRepo: 'https://github.com/FabKaiz/portfolio1',
    img: images.firstPortfolio,
    codeLanguage: 'HTML, CSS, JavaScript',
  },
  {
    id: 19,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://analytics-landing-react.netlify.app/',
    projectRepo: 'https://github.com/FabKaiz/analytics-landing-react',
    figmaLink:
      'https://www.figma.com/file/K8RIvVtJKHdXIqjpAPe97y/Analytics-%E2%80%94-Landing-Page-Design',
    img: images.analytics,
    codeLanguage: 'React et Scss',
  },
  {
    id: 5,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    figmaLink:
      'https://www.figma.com/file/KawxNnCZ1epHjQu0wSqlG2/Food-delivery-app-Ui-kit?node-id=0%3A1',
    projectSite: 'https://bella-olonje-delivery.netlify.app/',
    projectRepo: 'https://github.com/FabKaiz/food-delivery-app',
    img: images.foodDelivery,
    codeLanguage: 'React',
  },
  {
    id: 6,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://travel-advisor-fabkaiz.netlify.app/',
    projectRepo: 'https://github.com/FabKaiz/travel-advisor-react',
    img: images.Port12,
    codeLanguage:
      'React, Google maps API, Travel Advisor et Weather API, MaterialUI',
  },
  {
    id: 7,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://nextjs-real-estate-nu.vercel.app/',
    projectRepo: 'https://github.com/FabKaiz/nextjs-real-estate',
    img: images.Port11,
    codeLanguage: 'NextJs, ChakraUi, millify, axios, NProgress, BayutAPI',
  },
  {
    id: 8,
    title: 'Pen reveal',
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://fabkaiz.github.io/gsap3-pen-reveal/',
    projectRepo: 'https://github.com/FabKaiz/gsap3-pen-reveal',
    img: images.Port9,
    codeLanguage: 'JavaScript, ScrollTrigger, GSAP',
  },
  {
    id: 13,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://barbajs-gsap.netlify.app/',
    projectRepo: 'https://github.com/FabKaiz/barbajs-101',
    img: images.barbajsGsap,
    codeLanguage: 'BarbaJs, GSAP and JavaScript',
  },
  {
    id: 9,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://fabkaiz.github.io/gsap-slider-office/',
    projectRepo: 'https://github.com/FabKaiz/gsap3-slider-office',
    img: images.Port8,
    codeLanguage: 'JavaScript, GSAP',
  },
  {
    id: 10,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://www.chin-up.xyz/',
    projectRepo: 'https://github.com/fannymugnier/chin-up',
    img: images.Port1,
    codeLanguage: 'Ruby on Rails, JavaScript et Scss',
    youtubeLink:
      'https://www.youtube.com/watch?v=hJlf25bwRkI&list=PLwqwOtDwK_Zar-JrPOEAMDwYRiGay7Xw6&ab_channel=LeWagonLyon',
  },
  {
    id: 11,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://fabkaiz.github.io/snake-game-javascript/',
    projectRepo: 'https://github.com/FabKaiz/snake-game-javascript',
    img: images.Port4,
    codeLanguage: '',
  },
  {
    id: 12,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://fabkaiz.github.io/meme-generator-react/',
    projectRepo: 'https://github.com/FabKaiz/meme-generator-react',
    img: images.memeGenerator,
    codeLanguage: 'Meme API et React',
  },
  {
    id: 14,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://barbajs-css.netlify.app/',
    projectRepo: 'https://github.com/FabKaiz/barbajs-101',
    img: images.barbajsCss,
    codeLanguage: 'BarbaJs, Scss et JavaScript',
  },
  {
    id: 15,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    figmaLink:
      'https://www.frontendmentor.io/challenges/sunnyside-agency-landing-page-7yVs3B6ef',
    projectSite: 'https://sunnyside-vue.web.app/',
    projectRepo: 'https://github.com/FabKaiz/sunnyside-agency',
    img: images.Port7,
    codeLanguage: 'Vue, Scss',
  },
  {
    id: 16,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://find-coach-c96a2.web.app/coaches',
    projectRepo: 'https://github.com/FabKaiz/find-coach-vue',
    img: images.Port6,
    codeLanguage: 'VueJS',
  },
  {
    id: 17,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://fabkaiz.github.io/Javascript-component/',
    projectRepo: 'https://github.com/FabKaiz/Javascript-component',
    img: images.Port3,
    codeLanguage: 'JavaScript',
  },
  {
    id: 18,
    title: 'Title',
    description: `Lorem ipsum dolor sit amet consectetur, consectetur adipiscing elit sed`,
    projectSite: 'https://grab-a-star.herokuapp.com/',
    img: images.Port2,
    codeLanguage: 'Ruby on Rails',
  },
]

const skills = [
  // FRONTEND
  {
    id: 1,
    name: 'Creativity',
    logo: images.html,
  },
  {
    id: 2,
    name: 'Title',
    logo: images.sass,
  },
  {
    id: 3,
    name: 'Title',
    logo: images.javascript,
  },
  {
    id: 4,
    name: 'Title',
    logo: images.vue,
  },
  {
    id: 5,
    name: 'Title',
    logo: images.react,
  },
  {
    id: 5,
    name: 'Title',
    logo: images.nextjsIcon,
  },
  // BACKEND
  {
    id: 6,
    name: 'Title',
    logo: images.ruby,
  },
  {
    id: 7,
    name: 'Title',
    logo: images.rails,
  },
  {
    id: 8,
    name: 'Title',
    logo: images.db,
  },
  // TOOLS
  {
    id: 9,
    name: 'Title',
    logo: images.figma,
  },
  {
    id: 10,
    name: 'Title',
    logo: images.heroku,
  },
  {
    id: 11,
    name: 'Title',
    logo: images.github,
  },
  {
    id: 12,
    name: 'Title',
    logo: images.hotjar,
  },
  {
    id: 13,
    name: 'Title',
    logo: images.firebase,
  },
  {
    id: 14,
    name: 'Title',
    logo: images.netlify,
  },
  {
    id: 15,
    name: 'Title',
    logo: images.jest,
  },
  {
    id: 16,
    name: 'Title',
    logo: images.mongodb,
  },
]

const qualification = [
  {
    year: 2022,
    title: 'Lorem Ipsum',
    description: 'School or Organization',
  },
  {
    year: 2022,
    title: 'Lorem Ipsum',
    description: 'School or Organization',
    className: 'opacity-0',
  },
  {
    year: 2022,
    title: 'Lorem Ipsum',
    description: 'School or Organization',
    className: 'opacity-0',
  },
  {
    year: 2022,
    title: 'Lorem Ipsum',
    description: 'School or Organization',
    className: 'opacity-0',
  },
  {
    year: 2021,
    title: 'Lorem Ipsum',
    description: 'School or Organization',
  },
  {
    year: 2021,
    title: 'Lorem Ipsum',
    description: 'School or Organization',
    className: 'opacity-0',
  },
  {
    year: 2021,
    title: 'Lorem Ipsum',
    description: 'School or Organization',
    className: 'opacity-0',
  },
  {
    year: 2021,
    title: 'Lorem Ipsum',
    description: 'School or Organization',
    className: 'opacity-0',
  },
]

// eslint-disable-next-line import/no-anonymous-default-export
export default { projects, skills, qualification }
